runOnDraft: true

# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: author

numberOfReviewers: 2

reviewers:
  - wmasamuel
  - yhjor
  
runOnDraft: true
