reviewers:
  # The default reviewers
  defaults:
    - team:software-engineering-reviewers # GitHub team

# files:
#   # Keys are glob expressions.
#   # You can assign groups defined above as well as GitHub usernames.
#   '**':
#     - team:software-engineering-reviewers

options:
  ignore_draft: false
